grails:
  controllers:
    upload:
      maxFileSize: 5MB
      maxRequestSize: 5MB
      server:
        tomcat:
          max-http-post-size: 5242880

  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: 'StCo.User'
        authorityJoinClassName: 'StCo.UserRole'
      authority:
        className: 'StCo.Role'
      password:
        algorithm: bcrypt

      # ================= Static Rules =================
      controllerAnnotations:
        staticRules:
          # API paths → permitAll
          - pattern: '/api/**'
            access: ['permitAll']

          # GSP pages → login required
          - pattern: '/student/**'
            access: ['IS_AUTHENTICATED_FULLY']
          - pattern: '/course/**'
            access: ['IS_AUTHENTICATED_FULLY']
          - pattern: '/enrollment/**'
            access: ['IS_AUTHENTICATED_FULLY']
          - pattern: '/admin/**'
            access: ['ROLE_ADMIN']
          - pattern: '/user/**'
            access: ['ROLE_USER','ROLE_ADMIN']

          # الصفحات العامة
          - pattern: '/'
            access: ['permitAll']
          - pattern: '/index'
            access: ['permitAll']
          - pattern: '/index.gsp'
            access: ['permitAll']
          - pattern: '/error'
            access: ['permitAll']
          - pattern: '/shutdown'
            access: ['permitAll']
          - pattern: '/assets/**'
            access: ['permitAll']
          - pattern: '/**/js/**'
            access: ['permitAll']
          - pattern: '/**/css/**'
            access: ['permitAll']
          - pattern: '/**/images/**'
            access: ['permitAll']
          - pattern: '/**/favicon.ico'
            access: ['permitAll']

          # أي شيء آخر يحتاج تسجيل دخول
          - pattern: '/**'
            access: ['IS_AUTHENTICATED_FULLY']

      # ================= Filter Chain =================
      filterChain:
        chainMap:
          # تجاهل الفلاتر للأصول الثابتة
          - pattern: '/assets/**'
            filters: 'none'
          - pattern: '/**/js/**'
            filters: 'none'
          - pattern: '/**/css/**'
            filters: 'none'
          - pattern: '/**/images/**'
            filters: 'none'
          - pattern: '/**/favicon.ico'
            filters: 'none'

          # تعطيل الفلاتر للـ API → لا يحتاج login
          - pattern: '/api/**'
            filters: 'none'

          # باقي النظام محمي
          - pattern: '/**'
            filters: 'JOINED_FILTERS'

hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: root
  password: rahaf123

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://127.0.0.1:3306/students_db?useSSL=false&serverTimezone=UTC

  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

  production:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/students_db?useSSL=false&serverTimezone=UTC
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
