grails:
  controllers:
    upload:
      maxFileSize: 5MB       # الحد الأقصى لحجم الملف الواحد
      maxRequestSize: 5MB    # الحد الأقصى لحجم الطلب الكلي
      server:
        tomcat:
          max-http-post-size: 5242880

  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: 'StCo.User'
        authorityJoinClassName: 'StCo.UserRole'
      authority:
        className: 'StCo.Role'

hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: root
  password: rahaf123

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://127.0.0.1:3306/students_db?useSSL=false&serverTimezone=UTC

  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

  production:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/students_db?useSSL=false&serverTimezone=UTC
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
